Repository TeamWSH-Moida/Moida-Android, pull requests merged in 2024-02, with the labels that each got.

#10 setting CI
  .github/workflows/ Android CI.yml
Labels: 세팅

#11 🔗 :: (#9) setting CI
  build.gradle.kts
  buildSrc/build/classes/kotlin/main/Dependency$Ktlint.class
  buildSrc/build/classes/kotlin/main/Dependency$Test.class
  buildSrc/build/classes/kotlin/main/Dependency.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/constants.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/cacheable/last-build.bin
  buildSrc/build/kotlin/compileKotlin/local-state/build-history.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: 세팅

#13 CI 자바 버전 변경
  .github/workflows/ Android CI.yml
Labels: 세팅

#14 Update Android CI.yml
  .github/workflows/ Android CI.yml
Labels: 세팅

#17 🔗 :: (#16) ktlint 제거
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: 세팅

#21 🔗 :: (#20) navigation 세팅
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/migrations.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/androidTest/java/com/example/mogak_android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mogak_android/MainActivity.kt
  app/src/main/java/com/example/mogak_android/MogakApp.kt
  app/src/main/java/com/example/mogak_android/MogakApplication.kt
  app/src/main/java/com/example/mogak_android/navigation/AuthNavigation.kt
  app/src/main/java/com/example/mogak_android/theme/Color.kt
  app/src/main/java/com/example/mogak_android/theme/Theme.kt
  app/src/main/java/com/example/mogak_android/theme/Type.kt
  app/src/main/java/com/example/wsh_aos/MainActivity.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/mogak_android/ExampleUnitTest.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: 세팅

#24 🔗 :: (#23) .gitignore를 수정합니다
  .gitignore
Labels: 세팅

#28 🔗 :: (#27) retrofit 세팅
  data/src/main/java/com/example/data/api/ApiProvider.kt
  data/src/main/java/com/example/data/util/TokenInterceptor.kt
Labels: 세팅

#30 🔗 :: (#29) 폰트 추가하기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mogak_android/MainActivity.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  design-system/.gitignore
  design-system/build.gradle.kts
  design-system/consumer-rules.pro
  design-system/proguard-rules.pro
  design-system/src/main/AndroidManifest.xml
  design-system/src/main/java/com/example/design_system/foundation/MoidaColor.kt
  design-system/src/main/java/com/example/design_system/foundation/MoidaTypography.kt
  design-system/src/main/java/com/example/design_system/foundation/Theme.kt
  design-system/src/main/res/font/pretendard_regular.ttf
  design-system/src/main/res/font/pretendard_semi_bold.ttf
  design-system/src/test/java/com/example/design_system/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 세팅

#32 🔗 :: (#31) 프로젝트 이름 변경
  app/src/androidTest/java/com/example/moida_android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/moida_android/MainActivity.kt
  app/src/main/java/com/example/moida_android/MogakApp.kt
  app/src/main/java/com/example/moida_android/MogakApplication.kt
  app/src/main/java/com/example/moida_android/navigation/AuthNavigation.kt
  app/src/main/java/com/example/moida_android/theme/Color.kt
  app/src/main/java/com/example/moida_android/theme/Theme.kt
  app/src/main/java/com/example/moida_android/theme/Type.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/moida_android/ExampleUnitTest.kt
  buildSrc/src/main/java/ProjectProperties.kt
  settings.gradle.kts
Labels: 리펙토링

#34 🔗 :: (#33) 디자인 시스템 추가
  design-system/src/main/java/com/example/design_system/button/MoidaButton.kt
  design-system/src/main/java/com/example/design_system/button/MoidaButtonColors.kt
  design-system/src/main/java/com/example/design_system/text/MoidaText.kt
  design-system/src/main/java/com/example/design_system/util/MoidaClickable.kt
Labels: 디자인 시스템
